POST http://localhost:3030/books/create
Content-Type: application/json

{
  "title": "titolo del libro 12",
  "price": 299.99,
  "isFeatured": false,
  "author": "65fc75a27b2f58ce8dba94a7",
  "description": "lorem ipsum dolor sit amet."
}

####
GET http://localhost:3030/books
